apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-node-filedescriptor-limit
    role: alert-rules
  name: sre-node-filedescriptor-limit
  namespace: openshift-monitoring
spec:
  groups:
  - name: sre-controlplane-node-filedescriptor-limit
    rules:
    - alert: ControlPlaneNodeFileDescriptorLimitSRE
      # This is the same as the upstream alert, but groups by instance id (which is which node is affected)
      # and then only fires on the control-plane, infra, or master node roles.
      # See the ocm-agent folder for the WorkerNode version of this alert
      expr: |-
        group by (instance) (
          node_filefd_allocated{job="node-exporter"} * 100 / node_filefd_maximum{job="node-exporter"} >= 90
        )
        * on (instance) group_left ()group by (instance) (
          label_replace(kube_node_role{role=~"infra|control-plane|master"}, "instance", "$1", "node", "(.*)")
        )
      for: 15m
      labels:
        severity: critical
        namespace: openshift-monitoring
      annotations:
        message: "Kernel is predicted to exhaust file descriptors limit soon."
