---
# The current HAProxyReloadFail within 4.5.x, 4.6.x is currently a no-op.
# This alert self resolves ~ 5 mins. This alert will not be back ported until
# after the company recharge. Until backport is complete, the original alert
# will be sent to null reciver in CAM-operator and a custom SREP alert will
# replace it with a higher duration. 
# https://issues.redhat.com/browse/OSD-5751
# 4.7: https://bugzilla.redhat.com/show_bug.cgi?id=1892338 (in qa)
# 4.6 backport: https://bugzilla.redhat.com/show_bug.cgi?id=1896167  (assigned)
# 4.5 backport: https://bugzilla.redhat.com/show_bug.cgi?id=1896168 (assigned)
# TODO: remove HAProxyReloadFailSRE after HAProxyReloadFailSRE is available (Bugzilla-1892338)
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-haproxy-reload-fail
    role: alert-rules
  name: sre-haproxy-reload-fail
  namespace: openshift-monitoring
spec:
  groups:
  - name: sre-haproxy-reload-fails
    rules:
    - alert: HAProxyReloadFailSRE
      expr: increase(template_router_reload_fails[5m]) > 0
      for: 15m
      labels:
        severity: warning
        namespace: "{{ $labels.namespace }}"
      annotations:
        message: "HAProxy reloads have failed on {{ $labels.pod }}. Router is not respecting recently created or modified routes"
        link: "https://github.com/openshift/ops-sop/blob/master/v4/alerts/HAProxyReloadFailSRE.md"
