apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: rhmi-sre-cluster-admins
    role: alert-rules
  name: rhmi-sre-cluster-admins
  namespace: openshift-monitoring
spec:
  groups:
  - name: rhmi-sre-cluster-admins
    rules:
    - alert: ElevatingClusterAdminRHMISRE
      expr: openshift_group_user_account{group="layered-sre-cluster-admins"} == 1
      for: 130m
      labels:
        severity: warning
        namespace: redhat-rhmi
      annotations:
        message: RHMI SRE "{{ $labels.user }}"
          elevated to cluster-admin({{ $labels.group }}) more than 2 hours.