apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-oauth-server
    role: recording-rules
  name: sre-oauth-server
  namespace: openshift-monitoring
spec:
  groups:
  - name: sre-oauth-server
    rules:
      # aggregate the metrics under a new name to make sending these via remoteWrite easier
    - record: oauth_server_requests_total
      expr: apiserver_request_total{container="oauth-openshift"}
