apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-pv
    role: alert-rules
  name: sre-pv
  namespace: openshift-monitoring
spec:
  # https://issues.redhat.com/browse/OSD-3085
  # Existing OCP alerts covering core namespaces:
  # * KubePersistentVolumeUsageCritical
  # * KubePersistentVolumeFullInFourDays
  # Additional alerts for customers:
  # * KubePersistentVolumeUsageCriticalCustomer
  # * KubePersistentVolumeFullInFourDaysCustomer
  # Additional alerts for non-RHMI layered products:
  # * KubePersistentVolumeUsageCriticalLayeredProduct
  # * KubePersistentVolumeFullInFourDaysLayeredProduct
  groups:
  - name: sre-pv-customer
    rules:
      # This matches with the default KubePersistentVolumeUsageCritical; this rule inverts the regex match.
    - alert: KubePersistentVolumeUsageCriticalCustomer
      expr: |
        100
        * kubelet_volume_stats_available_bytes{job="kubelet",namespace!~"(^openshift-.*|^kube-.*|^default$|^redhat-.*)"}
        / kubelet_volume_stats_capacity_bytes{job="kubelet",namespace!~"(^openshift-.*|^kube-.*|^default$|^redhat-.*)"}
        < 3
      labels:
        severity: critical
        namespace: "{{ $labels.namespace }}"
      annotations:
        message: "The customer PersistentVolume claimed by {{ $labels.persistentvolumeclaim }} in Namespace {{ $labels.namespace }} is only {{ printf \"%0.2f\" $value }}% free."

      # This matches with the default KubePersistentVolumeFullInFourDays; this rule inverts the regex match.
    - alert: KubePersistentVolumeFullInFourDaysCustomer
      expr: |
        100
        * (kubelet_volume_stats_available_bytes{job="kubelet",namespace!~"(^openshift-.*|^kube-.*|^default$|^redhat-.*)"}
        / kubelet_volume_stats_capacity_bytes{job="kubelet",namespace!~"(^openshift-.*|^kube-.*|^default$|^redhat-.*)"})
        < 15 and predict_linear(kubelet_volume_stats_available_bytes{job="kubelet",namespace!~"(^openshift-.*|^kube-.*|^default$|^redhat-.*)"}[6h],
        4 * 24 * 3600) < 0
      labels:
        severity: warning
        namespace: "{{ $labels.namespace }}"
      annotations:
        message: "Based on recent sampling, the customer PersistentVolume claimed by {{ $labels.persistentvolumeclaim }} in Namespace {{ $labels.namespace }} is expected to fill up within four days. Currently {{ printf \"%0.2f\" $value }}% is available."

  - name: sre-pv-lp
    rules:
      # This matches with the default KubePersistentVolumeUsageCritical; this rule inverts the regex match.
    - alert: KubePersistentVolumeUsageCriticalLayeredProduct
      expr: |
        100
        * kubelet_volume_stats_available_bytes{job="kubelet",namespace=~"(^redhat-.*)",namespace!~"(^redhat-rhmi.*)"}
        / kubelet_volume_stats_capacity_bytes{job="kubelet",namespace=~"(^redhat-.*)",namespace!~"(^redhat-rhmi.*)"}
        < 3
      labels:
        severity: critical
        namespace: "{{ $labels.namespace }}"
      annotations:
        message: "The customer PersistentVolume claimed by {{ $labels.persistentvolumeclaim }} in Namespace {{ $labels.namespace }} is only {{ printf \"%0.2f\" $value }}% free."

      # This matches with the default KubePersistentVolumeFullInFourDays; this rule inverts the regex match.
    - alert: KubePersistentVolumeFullInFourDaysLayeredProduct
      expr: |
        100
        * (kubelet_volume_stats_available_bytes{job="kubelet",namespace=~"(^redhat-.*)",namespace!~"(^redhat-rhmi.*)"}
        / kubelet_volume_stats_capacity_bytes{job="kubelet",namespace=~"(^redhat-.*)",namespace!~"(^redhat-rhmi.*)"})
        < 15 and predict_linear(kubelet_volume_stats_available_bytes{job="kubelet",namespace=~"(^redhat-.*)",namespace!~"(^redhat-rhmi.*)"}[6h],
        4 * 24 * 3600) < 0
      labels:
        severity: warning
        namespace: "{{ $labels.namespace }}"
      annotations:
        message: "Based on recent sampling, the customer PersistentVolume claimed by {{ $labels.persistentvolumeclaim }} in Namespace {{ $labels.namespace }} is expected to fill up within four days. Currently {{ printf \"%0.2f\" $value }}% is available."
