apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-excessive-memory
    role: alert-rules
  name: sre-excessive-memory
  namespace: openshift-monitoring
spec:
  groups:
  - name: sre-excessive-memory
    rules:
    - alert: ExcessiveContainerMemoryWarningSRE
      # System namespaces, ignore prometheus/elasticsearch pods and customer monitoring, using more than 3GB of memory
      expr: container_memory_rss{namespace=~"(^openshift.*|^kube.*|^default$)",namespace!="openshift-customer-monitoring",container_name!="",container_name!="POD",pod!~"(^prometheus-k8s-.*|^elasticsearch-.*)"}/1024/1024/1024>3
      for: 30m
      labels:
        severity: warning
        namespace: "{{ $labels.namespace }}"
      annotations:
        message: System container {{ $labels.namespace }}/{{ $labels.pod_name }}/{{ $labels.container_name }}
          is using in excess of 3G of memory for over 30 minutes.
    - alert: ExcessiveContainerMemoryCriticalSRE
      # System namespaces, ignore prometheus/elasticsearch pods and customer monitoring, using more than 5GB of memory
      expr: container_memory_rss{namespace=~"(^openshift.*|^kube.*|^default$)",namespace!="openshift-customer-monitoring",container_name!="",container_name!="POD",pod!~"(^prometheus-k8s-.*|^elasticsearch-.*)"}/1024/1024/1024>5
      for: 30m
      labels:
        severity: critical
        namespace: "{{ $labels.namespace }}"
      annotations:
        message: System container {{ $labels.namespace }}/{{ $labels.pod_name }}/{{ $labels.container_name }}
          is using in excess of 5G of memory for over 30 minutes.
