# Existing KubeJob*Failed* alert fires regardless of successfully finished CronJob resulting in a frequent no-op pages. In case of single job failure, if a more recent job completed, the alert indicates an intermittent failure and requires no further investigation.
# Whereas KubeJob*Failing* alert fires if the Kubernetes Job is consecutively failing.
# Original alert will be sent to null receiver in CAM-operator and a custom SREP alert with improved expression will replace it.
# https://issues.redhat.com/browse/OSD-14058
# TODO: remove KubeJobFailingSRE after KubeJobFailing is available in upstream (https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/816)
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-kubejobfailing
    role: alert-rules
  name: sre-kubejobfailing
  namespace: openshift-monitoring
spec:
  groups:
  - name: sre-kubejobfailing-recording.rules
    rules:
    - record: job:kube_job_status_failed:sum
      expr: |
        clamp_max(job:kube_job_status_start_time:max, 1)
        * ON(job_name) GROUP_LEFT()
        (kube_job_status_failed{namespace=~"(openshift-.*|kube-.*|default)",job="kube-state-metrics"} > 0)
    - record: job:kube_job_status_start_time:max
      expr: |
        max(
         kube_job_status_start_time{namespace=~"(openshift-.*|kube-.*|default)",job="kube-state-metrics"}
         * ON(job_name,namespace) GROUP_RIGHT()
         kube_job_owner{owner_name!="",owner_name!="<none>"}
        )   
        BY (job_name, owner_name, namespace)
        == ON(owner_name) GROUP_LEFT()
        max(
         kube_job_status_start_time{namespace=~"(openshift-.*|kube-.*|default)",job="kube-state-metrics"}
         * ON(job_name,namespace) GROUP_RIGHT()
         kube_job_owner{owner_name!="",owner_name!="<none>"}
        )   
        BY (owner_name)
  - name: sre-kubejobfailing
    rules:
    - alert: KubeJobFailingSRE
      expr: |
        job:kube_job_status_failed:sum
      for: 15m
      labels:
        severity: warning
        namespace: '{{ $labels.namespace }}'
      annotations:
        description: 'Job {{ $labels.namespace }}/{{ $labels.job_name }} is failing to complete.'
        summary: 'Job is failing to complete.'
        link: 'https://github.com/openshift/ops-sop/blob/master/v4/alerts/KubeJobFailed.md'
        