---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: osd-rebalance-infra-nodes-openshift-monitoring
  namespace: openshift-monitoring
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - delete
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - delete
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - get