---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: osd-rebalance-infra-nodes-openshift-security
  namespace: openshift-security
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - delete