deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
  - key: api.openshift.com/product
    operator: NotIn
    values: ["rosa"]
  - key: api.openshift.com/fedramp
    operator: NotIn
    values: ["true"]
