deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  resourceApplyMode: Upsert
  matchLabelsApplyMode: "AND"
  matchExpressions:
    - key: hive.openshift.io/version-major-minor
      operator: NotIn
      values: ["4.1", "4.2", "4.3", "4.4", "4.5", "4.6", "4.7", "4.8"]
    - key: ext-managed.openshift.io/disable-debugging-handlers
      operator: NotIn
      values: ["true"]
