deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchLabelsApplyMode: "OR"
  matchExpressions:
    - key: hive.openshift.io/version-major-minor
      operator: In
      values: ["4.5"]
    - key: ext-managed.openshift.io/uwm-disabled
      operator: In
      values: ["true"]
policy:
  destination: "acm-policies"
  clusterSelectors:
    hypershift.open-cluster-management.io/hosted-cluster: "true"
    ext-managed.openshift.io/uwm-disabled: "true"

