apiVersion: avo.openshift.io/v1alpha2
kind: VpcEndpoint
metadata:
  name: splunk
  namespace: openshift-security
spec:
  serviceName: com.amazonaws.vpce.us-gov-west-1.vpce-svc-06225ed6e3620e8e1
  securityGroup:
    ingressRules:
      - fromPort: 9997
        toPort: 9997
        protocol: tcp
  vpc:
    autoDiscoverSubnets: true
  customDns:
    route53PrivateHostedZone:
      autoDiscoverPrivateHostedZone: true
      record:
        hostname: "splunk"
        externalNameService:
          name: indexer
