apiVersion: imageregistry.operator.openshift.io/v1
applyMode: AlwaysApply
kind: ImagePruner
name: cluster
namespace: openshift-image-registry
patch: '{"spec":{"keepYoungerThan":86400000000000, "ignoreInvalidImageReferences": true, "schedule": "0 */1 * * *", "suspend": false, "affinity": {"nodeAffinity": {"preferredDuringSchedulingIgnoredDuringExecution": [{"preference": {"matchExpressions": [{"key": "node-role.kubernetes.io/infra", "operator": "Exists"}]}, "weight": 1}]}}, "tolerations": [{"effect": "NoSchedule", "key": "node-role.kubernetes.io/infra", "operator": "Exists"}]}}'
patchType: merge
