deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchLabels:
      api.openshift.com/addon-kas-fleetshard-operator: "true"
      api.openshift.com/addon-kas-fleetshard-operator-qe: "true"
      api.openshift.com/addon-managed-kafka: "true"
      api.openshift.com/addon-managed-kafka-qe: "true"
  matchLabelsApplyMode: "OR"
