apiVersion: managed.openshift.io/v1alpha1
kind: SubjectPermission
metadata:
  name: backplane-odf-ocs-consumer-admins
  namespace: openshift-rbac-permissions
spec:
  permissions:
  - clusterRoleName: admin
    namespacesAllowedRegex: (^openshift-storage$)
  - clusterRoleName: backplane-ocs-consumer-cr-admins
    namespacesAllowedRegex: (^openshift-storage$)
  subjectKind: Group
  subjectName: system:serviceaccounts:openshift-backplane-odf
