apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  templates:
    login:
      name: rosa-oauth-templates-login
    providerSelection:
      name: rosa-oauth-templates-providers
    error: 
      name: rosa-oauth-templates-errors
