#Create a namespace called 'openshift-managed-rbac-policies' on service cluster that the generated policies are later created in.
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-mananged-rbac-policies
