apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backplane-cee-management-cluster-cluster
rules:
- apiGroups:
  - work.open-cluster-management.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.open-cluster-management.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy.open-cluster-management.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hypershift.openshift.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch  

