---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bz1980755
rules:
- apiGroups:
  - operators.coreos.com
  resources:
  - clusterserviceversions
  - installplans                 
  - subscriptions
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - delete
