---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: bz1980755
  namespace: openshift-sre-pruning
spec:
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  concurrencyPolicy: Replace
  schedule: "25 3 * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - preference:
                  matchExpressions:
                  - key: node-role.kubernetes.io/infra
                    operator: Exists
                weight: 1
          tolerations:
            - effect: NoSchedule
              key: node-role.kubernetes.io/infra
              operator: Exists
          serviceAccountName: bz1980755
          restartPolicy: Never
          containers:
          - name: bz1980755
            image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
            imagePullPolicy: Always
            args:
            - /bin/bash
            - -c
            - |
              set -e
              set -o nounset
              set -o pipefail

              TEMPDIR=$(mktemp -d)

              echo "Checking for impacted subscriptions.."
              IMPACTED_SUBS=$(oc get sub -A -l 'hive.openshift.io/managed=true' -o json | jq -r '.items[] | select(.status.conditions[].reason == "ConstraintsNotSatisfiable") | "\(.metadata.namespace),\(.metadata.name)"')

              if [[ -z "${IMPACTED_SUBS}" ]]; then
                 echo "No impacted subscriptions found."
                 exit 0
              fi

              while read subAndNS; do

                  ns=$(echo "${subAndNS}" | cut -d, -f 1)
                  sub=$(echo "${subAndNS}" | cut -d, -f 2)

                  if [[ -z "${ns}" || -z "${sub}" ]]; then
                      continue
                  fi

                  echo "Will re-install subscription ${ns}/${sub}"
                  oc get subscriptions.operators.coreos.com -n "${ns}" "${sub}" -ojson | grep -v "kubectl.kubernetes.io/last-applied-configuration" > ${TEMPDIR}/${sub}.yaml

                  for ip in `oc get installplans.operators.coreos.com -n "${ns}" -o jsonpath="{.items[?(@.metadata.ownerReferences[*].name=='${sub}')].metadata.name}"`; do
                      echo "Removing installplan ${ip}"
                      oc delete installplans.operators.coreos.com -n "${ns}" $ip
                  done

                  for csv in `oc get clusterserviceversions.operators.coreos.com -n "${ns}" -o jsonpath="{.items[*].metadata.name}"`; do
                      if [[ "${csv}" =~ ^${sub}.* || "openshift-${csv}" =~ ^${sub}.* ]]; then
                          echo "Removing CSV ${csv}"
                          oc delete clusterserviceversions.operators.coreos.com -n "${ns}" "${csv}"
                      fi
                  done

                  echo "Removing subscription ${sub}"
                  oc delete subscriptions.operators.coreos.com  -n "${ns}" "${sub}"

                  echo "Restarting catalog-operator to clear cache"
                  oc delete pod -n openshift-operator-lifecycle-manager -l app=catalog-operator --wait=true

                  echo "Recreating subscription ${sub}"
                  oc create -f ${TEMPDIR}/${sub}.yaml

              done <<< "${IMPACTED_SUBS}"
