apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pcap-dedicated-admins
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - "pcap-dedicated-admins"
  verbs:
  - use
