apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pcap-dedicated-admins
subjects:
- kind: Group
  name: dedicated-admins
roleRef:
  kind: ClusterRole
  name: pcap-dedicated-admins
  apiGroup: rbac.authorization.k8s.io
