apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: osd-disable-cpms
  namespace: openshift-machine-api
rules:
- apiGroups:
  - machine.openshift.io
  resources:
  - controlplanemachinesets
  verbs:
  - delete
