apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: osd-disable-cpms
  namespace: openshift-machine-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: osd-disable-cpms
subjects:
- kind: ServiceAccount
  name: osd-disable-cpms
  namespace: openshift-machine-api
