deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  resourceApplyMode: Sync
  matchExpressions:
  ## This will be removed once OSD-14568 has been completed
  - key: hive.openshift.io/version-major-minor
    operator: In
    values: ["4.12"]
