apiVersion: avo.openshift.io/v1alpha2
kind: VpcEndpoint
metadata:
  name: splunk
  namespace: openshift-security
spec:
  serviceName: com.amazonaws.vpce.us-gov-east-1.vpce-svc-0838533cd2d6d2b8b
  securityGroup:
    ingressRules:
      - fromPort: 9997
        toPort: 9997
        protocol: tcp
  vpc:
    autoDiscoverSubnets: true
  customDns:
    route53PrivateHostedZone:
      autoDiscoverPrivateHostedZone: true
      record:
        hostname: "splunk"
        externalNameService:
          name: indexer
