apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-alerts-stuck-volumes
    role: alert-rules
  name: sre-alerts-stuck-volumes
  namespace: openshift-monitoring
spec:
  groups:
  - name: sre-alerts-stuck-volumes
    rules:
    - alert: EbsVolumeStuckAttaching5MinSRE
      expr: ebs_volume_state{ebs_volume_state="attaching"} > 0
      for: 5m
      labels:
        severity: warning
        namespace: openshift-monitoring
    - alert: EbsVolumeStuckAttaching10MinSRE
      expr: ebs_volume_state{ebs_volume_state="attaching"} > 0
      for: 10m
      labels:
        severity: critical
        namespace: openshift-monitoring
    - alert: EbsVolumeStuckDetaching5MinSRE
      expr: ebs_volume_state{ebs_volume_state="detaching"} > 0
      for: 5m
      labels:
        severity: warning
        namespace: openshift-monitoring
    - alert: EbsVolumeStuckDetaching10MinSRE
      expr: ebs_volume_state{ebs_volume_state="detaching"} > 0
      for: 10m
      labels:
        severity: critical
        namespace: openshift-monitoring