apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: osd-cluster-ready
  namespace: openshift-monitoring
rules:
# Service account needs to be able to get pods and exec on them
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
