apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: osd-cluster-ready
  namespace: openshift-machine-api
rules:
- apiGroups:
  - machine.openshift.io
  resources:
  - machines
  verbs:
  - list
