apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: osd-cluster-ready
  namespace: openshift-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: osd-cluster-ready
subjects:
- kind: ServiceAccount
  name: osd-cluster-ready
  namespace: openshift-monitoring
