apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: osd-cluster-ready
rules:
- apiGroups:
  - config.openshift.io
  resources:
  - clusterversions
  verbs:
  - get
- apiGroups:
  - "apps"
  resources:
  - daemonsets
  - replicasets
  verbs:
  - list
  - get
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - list
- apiGroups:
  - config.openshift.io
  resources:
  - clusteroperators
  verbs:
  - list
