apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: osd-cluster-ready
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: osd-cluster-ready
subjects:
- kind: ServiceAccount
  name: osd-cluster-ready
  namespace: openshift-monitoring
