---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: sre-pod-network-connectivity-check-pruner
  namespace: openshift-network-diagnostics
  annotations:
    kubernetes.io/description: Mitigate https://issues.redhat.com/browse/OCPBUGS-1341 by pruning leaked PodNetworkConnectivityChecks.
