---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sre-pod-network-connectivity-check-pruner
  namespace: openshift-network-diagnostics
  annotations:
    kubernetes.io/description: Mitigate https://issues.redhat.com/browse/OCPBUGS-1341 by pruning leaked PodNetworkConnectivityChecks.
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sre-pod-network-connectivity-check-pruner
subjects:
- kind: ServiceAccount
  name: sre-pod-network-connectivity-check-pruner
  namespace: openshift-network-diagnostics
