---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sre-pod-network-connectivity-check-pruner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node-reader
subjects:
- kind: ServiceAccount
  name: sre-pod-network-connectivity-check-pruner
  namespace: openshift-network-diagnostics
