apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    managed.openshift.io/aggregate-to-dedicated-admins: "cluster"
  name: velero-schedule-admins-cluster
rules:
- apiGroups:
  - velero.io
  attributeRestrictions: null
  resources:
  - schedules
  verbs:
  - "*"
