apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backplane-lpsre-package-operator-project
rules:
- apiGroups:
  - package-operator.run
  resources:
  - packages
  - objectdeployments
  - objectsets
  - objecttemplates
  verbs:
  - get
  - list
  - watch
  # Required to recover in case of outages.
  # e.g.
  # - finalizer stuck blocking Add-on deletion
  # - data loss of child resource, breaking revision linearity
  #   (https://package-operator.run/docs/concepts/revisions/)
  # - dynamic object watch missing an event due to a bug or high load
  - update
  - patch
  - create
  - delete
