kind: Namespace
apiVersion: v1
name: openshift-kube-apiserver
applyMode: AlwaysApply
# https://issues.redhat.com/browse/OSD-4230
patch: |-
  { "metadata": {"labels": {"name":"openshift-kube-apiserver"} } }
patchType: merge
