apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dedicated-admins-registry-cas-cluster
rules:
# For: https://issues.redhat.com/browse/OSD-3144
# https://docs.openshift.com/container-platform/4.3/builds/setting-up-trusted-ca.html#configmap-adding-ca_setting-up-trusted-ca
# allow view and edit, not create or delete, on 'cluster' images.config.openshift.io
- apiGroups:
  - config.openshift.io
  resources:
  - images
  resourceNames:
  - cluster
  verbs:
  - get
  - list
  - watch
  - patch
  - update
