apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dedicated-admins-registry-cas-project
  namespace: openshift-config
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: dedicated-admins
- kind: Group
  name: system:serviceaccounts:dedicated-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dedicated-admins-registry-cas-project
