apiVersion: cloudingress.managed.openshift.io/v1alpha1
kind: APIScheme
metadata:
  name: rh-api
  namespace: openshift-cloud-ingress-operator
  annotations:
    allowedCIDRBlocks: ${ALLOWED_CIDR_BLOCKS}
spec:
  managementAPIServerIngress:
    enabled: true
    dnsName: rh-api
    allowedCIDRBlocks: ${{ALLOWED_CIDR_BLOCKS}}
