apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-codeready-workspaces
  namespace: openshift-codeready-workspaces
spec:
  serviceAccount:
    metadata:
      creationTimestamp: null
  targetNamespaces:
  - openshift-codeready-workspaces
