deploymentMode: SelectorSyncSet
selectorSyncSet:
  matchExpressions:
  - key: hive.openshift.io/version-major-minor
    operator: In
    values: ["4.10"]
  - key: api.openshift.com/gate-sts
    operator: In
    values: ["4.11"]
  - key: api.openshift.com/sts
    operator: In
    values: ["true"]
