apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: suricata-rolebinding
  namespace: openshift-suricata
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: suricata-role
subjects:
- kind: ServiceAccount
  name: suricata-sa
  namespace: openshift-suricata
