apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: suricata
  namespace: openshift-suricata
spec:
  selector:
    matchLabels:
      name: suricata
  template:
    metadata:
      labels:
        name: suricata
    spec:
      containers:
      - env:
        - name: OO_PAUSE_ON_START
          value: "false"
        image: quay.io/app-sre/suricata@sha256:f20d62e34c37b4761d5625594a5adf1c62bc44452e74d31d989a1cbd13c01962
        imagePullPolicy: IfNotPresent
        name: suricata
        resources:
          limits:
            cpu: 900m
            memory: 900Mi
          requests:
            cpu: 100m
            memory: 50Mi
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /host/
          name: host-filesystem
      - name: log-cleaner
        image: quay.io/app-sre/log-cleaner@sha256:11ad54f9bcdcb551839974aa3bde2b2404a168b407358b81bd4164a89242d53c
        volumeMounts:
        - mountPath: /host/
          name: host-filesystem        
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: suricata-sa
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: /
        name: host-filesystem
