deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
  - key: environment
    operator: In
    values: ["integration"]
  - key: ext-managed.openshift.io/hive-shard
    operator: In
    values: ["true"]
