apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: custom-etcd-prometheus-rules
  namespace: openshift-etcd-operator
spec:
  groups:
  - name: etcd
    rules:
    - record: etcd_revision_stddev_sre
      expr: |
        -etcd_debugging_mvcc_compact_revision
          + on (job, namespace) group_left (max_instance, max_pod)
        label_replace(
          label_replace(
            topk by (job,namespace) (1, etcd_debugging_mvcc_compact_revision),
            "max_instance", "$1", "instance", "(.*)"
          ),
          "max_pod", "$1", "pod", "(.*)"
        )
    - alert: etcdDivergentRevisionsSRE
      annotations:
        description: etcd is reporting divergent member revisions, with a pod
          {{ $labels.pod }} on instance {{ $labels.instance }} trailing
          {{ $value }} compacted revisions behind pod {{ $labels.max_pod }} on
          instance {{ $labels.max_instance }}. Members may be stuck or, in
          extreme circumstances, split brained.
        summary: etcd is reporting divergent member revisions.
      expr: etcd_revision_stddev_sre > 0
      for: 40m
      labels:
        severity: critical
        namespace: openshift-etcd-operator
