apiVersion: managed.openshift.io/v1alpha1
kind: SubjectPermission
metadata:
  name: backplane-lpsre-acs-admins-project
  namespace: openshift-rbac-permissions
spec:
  permissions:
  - clusterRoleName: view
    namespacesAllowedRegex: (^redhat-acs-fleetshard$|^rhacs-.*)
  - clusterRoleName: backplane-lpsre-acm-admins-project
    namespacesAllowedRegex: (^redhat-acs-fleetshard$|^rhacs-.*)
  subjectKind: Group
  subjectName: system:serviceaccounts:openshift-backplane-lpsre
