apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backplane-acs-lpsre-admins-project
rules:
- apiGroups:
  - platform.stackrox.io
  resources:
  - centrals
  - securedclusters
  verbs:
  - get
  - list
  - watch
