apiVersion: monitoring.rhobs/v1
kind: Prometheus
name: hypershift-monitoring-stack
namespace: openshift-observability-operator
applyMode: Sync
patch: '{"spec":{"nodeSelector":{"node-role.kubernetes.io/obo":""}}}'
patchType: merge
