apiVersion: monitoring.rhobs/v1
applyMode: Sync
kind: Prometheus
name: hypershift-monitoring-stack
namespace: openshift-observability-operator
patch: '{"spec":{"tolerations":[{"effect":"NoSchedule","key":"obo","value":"true"}]}}'
patchType: merge
