deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
  - key: environment
    operator: In
    values: ["integration"]
  - key: ext-hypershift.openshift.io/cluster-type
    operator: In
    values: ["service-cluster", "management-cluster"]
