apiVersion: config.openshift.io/v1
applyMode: AlwaysApply
kind: OAuth
name: cluster
namespace: default
patch: '{"spec":{"tokenConfig":{"accessTokenMaxAgeSeconds":604800, "accessTokenInactivityTimeout": "168h"}}}'
patchType: merge
