---
deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  resourceApplyMode: Sync
  matchExpressions:
    - key: hive.openshift.io/version-major-minor-patch
      operator: In
      values:
        - 4.11.0
        - 4.11.1
        - 4.11.2
        - 4.11.3
        - 4.11.4
        - 4.11.5
        - 4.11.6
        - 4.11.7
        - 4.11.8
        - 4.11.9
        - 4.11.10
        - 4.11.11
        - 4.11.12
        - 4.11.13
        - 4.11.14
        - 4.11.15
        - 4.11.16
        - 4.11.17
        - 4.11.18
