apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    managed.openshift.io/aggregate-to-dedicated-admins: "project"
  name: dedicated-admins-manage-operators
rules:
- apiGroups:
  - operators.coreos.com
  resources:
  - "*"
  verbs:
  - "*"
