apiVersion: managed.openshift.io/v1alpha1
kind: SubjectPermission
metadata:
  name: dedicated-admins-customer-monitoring
  namespace: openshift-rbac-permissions
spec:
  subjectKind: Group
  subjectName: dedicated-admins
  permissions:
    - 
      clusterRoleName: dedicated-admins-project
      namespacesAllowedRegex: "^openshift-customer-monitoring$"
    -
      clusterRoleName: admin 
      namespacesAllowedRegex: "^openshift-customer-monitoring$"
