apiVersion: batch/v1
kind: Job
metadata:
    name: osd-cluster-ready
    namespace: openshift-monitoring
spec:
    # NOTE: We're making this ridiculously high to ensure that the
    # actual code gets a chance to run to completion. However, consumers
    # should implement a sensible timeout rather than waiting forever.
    backoffLimit: 500
    template:
        metadata:
            name: osd-cluster-ready
            labels:
                # Keep this in sync with image
                managed.openshift.io/version: "v0.1.108-cd4483a"
        spec:
            containers:
            - name: osd-cluster-ready
              # Keep the `managed.openshift.io/version` label in sync
              # with this
              image: "quay.io/app-sre/osd-cluster-ready@sha256:f70aa8033565fc73c006acb9199845242b1f729cb5a407b5174cf22656b4e2d5"
              command: ["/root/main"]
            restartPolicy: OnFailure
            serviceAccountName: osd-cluster-ready
