apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dedicated-admins-user-workload-monitoring-create-cm
  namespace: openshift-user-workload-monitoring
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - '*'