apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dedicated-admins-user-workload-monitoring-manage-am-secret
  namespace: openshift-user-workload-monitoring
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - alertmanager-user-workload
  verbs:
  - get
  - list
  - watch
  - update
  - patch
