apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scanner-rolebinding
  namespace: openshift-scanning
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scanner-role
subjects:
- kind: ServiceAccount
  name: scanner-sa
  namespace: openshift-scanning
