deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
    - key: hive.openshift.io/version-major-minor
      operator: NotIn
      values: ["4.5"]
    - key: ext-managed.openshift.io/uwm-disabled
      operator: NotIn
      values: ["true"]
policy:
  destination: "acm-policies"
  clusterSelectors: 
     ext-managed.openshift.io/uwm-disabled: "false"
     hypershift.open-cluster-management.io/hosted-cluster: "true"

