apiVersion: managed.openshift.io/v1alpha1
kind: SubjectPermission
metadata:
  name: backplane-nvidia-gpu-admins
  namespace: openshift-rbac-permissions
spec:
  permissions:
  - clusterRoleName: admin
    namespacesAllowedRegex: (^redhat-nvidia-gpu-addon$)
  subjectKind: Group
  subjectName: system:serviceaccounts:openshift-backplane-addon-nvidia-gpu
