apiVersion: ocmagent.managed.openshift.io/v1alpha1
kind: ManagedNotification
metadata:
  name: sre-proxy-managed-notifications
  namespace: openshift-ocm-agent-operator
spec:
  notifications:
    - name: AdditionalTrustBundleCAExpiring
      severity: Warning
      summary: "Additional Trust Bundle CA Expiring"
      activeBody: |-
        Your cluster requires you to take action because one of the Certificate Authority (CA) certificates in the Additional Trusted CA Bundle you have set for your cluster is due to expire. To avoid any potential disruption of service or cluster availability caused by the expiration of the CA certificate, please ensure your Additional Trusted CA Bundle is updated with any new CA certificates required. For more information, please refer to https://docs.openshift.com/rosa/networking/configuring-cluster-wide-proxy.html#trust_bundle_responsibilities_cluster-wide-proxy-configuration
      resendWait: 48
      resolvedBody: |-
        Your cluster's Additional Trusted CA Bundle is detected as no longer containing any Certificate Authority (CA) certificates that are due for imminent expiry. No further action on this issue is required.
    - name: AdditionalTrustBundleCAExpired
      severity: Error
      summary: "Additional Trust Bundle CA Expired"
      activeBody: |-
        Your cluster requires you to take action because one of the Certificate Authority (CA) certificates in the Additional Trusted CA Bundle you have added to your cluster has now reached its expiration date. To avoid any potential disruption of service or cluster availability caused by the expiration of the CA certificate, please ensure your Additional Trusted CA Bundle is updated with any new CA certificates required and remove the expired CA certficates. For more information, please refer to https://docs.openshift.com/rosa/networking/configuring-cluster-wide-proxy.html#trust_bundle_responsibilities_cluster-wide-proxy-configuration
      resendWait: 24
      resolvedBody: |-
        Your cluster's Additional Trusted CA Bundle is detected as no longer containing any Certificate Authority (CA) certificates that are expired. No further action on this issue is required.
    - name: AdditionalTrustBundleCAInvalid
      severity: Error
      summary: "Additional Trust Bundle CA Invalid"
      activeBody: |-
        Your cluster requires you to take action because one of the Certificate Authority (CA) certificates in the Additional Trusted CA Bundle you have added to your cluster is detected as unparseable or invalid. Please ensure your Additional Trusted CA Bundle represents a bundle of one or more PEM-encoded X.509 certificates that are all concatenated together. For more information, please refer to https://docs.openshift.com/rosa/networking/configuring-cluster-wide-proxy.html#trust_bundle_responsibilities_cluster-wide-proxy-configuration 
      resendWait: 24
      resolvedBody: |-
        Your cluster's Additional Trusted CA Bundle is detected as no longer containing any invalid Certificate Authority (CA) certificates. No further action on this issue is required.
    - name: ClusterProxyNetworkDegraded
      severity: Error
      summary: "Cluster-wide Proxy failing readiness checks"
      activeBody: |-
        Your cluster requires you to take action because your configured cluster-wide proxy is failing to satisfy readiness endpoint reachability checks that can confirm its correct operation. Please verify the availability of your cluster-wide proxy and its ability to proxy egress network traffic from the cluster. For more information on management of the cluster-wide proxy, please refer to https://docs.openshift.com/rosa/networking/configuring-cluster-wide-proxy.html
      resendWait: 24
      resolvedBody: |-
        Your cluster's cluster-wide proxy is no longer raising any errors concerning network egress. No further action on this issue is required.
