apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
    name: rbac-policies
policyDefaults:
    namespace: openshift-managed-rbac-policies
    placement:
        clusterSelectors:
            hypershift.open-cluster-management.io/hosted-cluster: "true"
    remediationAction: enforce
    pruneObjectBehavior: "DeleteIfCreated"
policies:
    - name: #Filled by script
      manifests:
          # NOTE to use a path, the target directory must NOT have a `config.yaml` else it is included in the policy
          - path: #Filled by script
