deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
  - key: api.openshift.com/product
    operator: In
    values: ["rosa"]
  applyBehavior: "CreateOrUpdate"
  # use Upsert so if this configuration no longer applies it will not delete the resource in cluster . We should never delete console.
  resourceApplyMode: "Upsert"
policy:
  CreatePolicy: "yes"
  complianceType: "musthave"
