apiVersion: operator.openshift.io/v1
kind: Console
metadata:
  name: cluster
spec:
  managementState: Managed
  route:
  customization:
    brand: 
    documentationBaseURL: https://docs.openshift.com/rosa/
    customProductName: "Red Hat OpenShift Service on AWS"
    customLogoFile:
      name: rosa-brand-logo
      key: rosa-brand-logo.svg
