deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  resourceApplyMode: "Sync"
  matchExpressions:
  - key: ext-managed.openshift.io/extended-logging-support
    operator: NotIn
    values: ["true"]
  - key: api.openshift.com/fedramp
    operator: NotIn
    values:
      - "true"