apiVersion: managed.openshift.io/v1alpha1
kind: SubjectPermission
metadata:
  name: sre-build-test
  namespace: openshift-rbac-permissions
spec:
  permissions:
  - clusterRoleName: admin
    namespacesAllowedRegex: "^openshift-build-test-.*$"
  subjectKind: User
  subjectName: system:serviceaccount:openshift-build-test:sre-build-test
