apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sre-build-test
  namespace: openshift-build-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sre-build-test
subjects:
- kind: ServiceAccount
  name: sre-build-test
  namespace: openshift-build-test
