apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sre-build-test
  namespace: openshift-build-test
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - list
  - delete
