apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-alerts-stuck-builds
    role: alert-rules
  name: sre-alerts-stuck-builds
  namespace: openshift-monitoring
spec:
  groups:
  - name: sre-alerts-stuck-builds
    rules:
    - alert: StuckNewBuilds3MinSRE
      expr: count(openshift_build_active_time_seconds{phase="New",exported_namespace=~"^openshift-build-test.*"} < time() - 180) > 0
      labels:
        severity: warning
        namespace: openshift-monitoring
    - alert: StuckPendingBuilds3MinSRE
      expr: count(openshift_build_active_time_seconds{phase="Pending",exported_namespace=~"^openshift-build-test.*"} < time() - 180) > 0
      labels:
        severity: warning
        namespace: openshift-monitoring