apiVersion: operator.openshift.io/v1
applyMode: AlwaysApply
kind: Console
name: cluster
patchType: merge
patch: >-
  {"metadata":{"annotations":{"telemetry.console.openshift.io/CLUSTER_TYPE":"ROSA","telemetry.console.openshift.io/SEGMENT_API_KEY":"${SEGMENT_API_KEY}"}}}
