---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hs-delete-custom-cmo-config
rules:
- apiGroups:
  - hive.openshift.io
  resources:
  - syncsets
  resourceNames:
  - "ext-cluster-monitoring-operator-config"
  verbs:
  - "*"
- apiGroups:
  - hive.openshift.io
  resources:
  - clusterdeployments
  verbs:
  - get
  - list
