---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hs-delete-custom-cmo-config
subjects:
- kind: ServiceAccount
  name: hs-delete-custom-cmo-config
  namespace: openshift-delete-custom-cmo-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hs-delete-custom-cmo-config
