apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backplane-cee-service-cluster-cluster
rules:
- apiGroups:
  - work.open-cluster-management.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - addon.open-cluster-management.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - agent.open-cluster-management.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch  
- apiGroups:
  - operator.open-cluster-management.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch  
- apiGroups:
  - policy.open-cluster-management.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch 
- apiGroups:
  - policy.open-cluster-management.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch 
