---
deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  resourceApplyMode: Sync
  matchExpressions:
    - key: hive.openshift.io/version-major-minor-patch
      operator: In
      values:
        - 4.10.0
        - 4.10.1
        - 4.10.2
        - 4.10.3
        - 4.10.4
        - 4.10.5
        - 4.10.6
        - 4.10.7
        - 4.10.8
        - 4.10.9
        - 4.10.10
        - 4.10.11
        - 4.10.12
        - 4.10.13
        - 4.10.14
        - 4.10.15
        - 4.10.16
        - 4.10.17
        - 4.10.18
        - 4.10.19
        - 4.10.20
        - 4.10.21
        - 4.10.22
        - 4.10.23
        - 4.10.24
        - 4.10.25
        - 4.10.26
        - 4.10.27
        - 4.10.28
        - 4.10.29
        - 4.10.30
        - 4.10.31
        - 4.10.32
        - 4.10.33
        - 4.10.34
        - 4.10.35
        - 4.10.36
        - 4.10.37
        - 4.10.38
        - 4.10.39
        - 4.10.40
        - 4.10.41
        - 4.10.42
        - 4.10.43
        - 4.10.44
        - 4.10.45
