apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dedicated-admins-openshift-strimzi
  namespace: openshift-strimzi
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - pods/log
  - events
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - operators.coreos.com
  resources:
  - subscriptions
  - clusterserviceversions
  verbs:
  - "*"
- apiGroups:
  - "monitoring.coreos.com"
  resources:
  - prometheusrules
  - servicemonitors
  - podmonitors
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - update
  - get
  - list
  - watch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kafka.strimzi.io
  resources:
  - "*"
  verbs:
  - "*"
