apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s-openshift-customer-monitoring
  namespace: openshift-customer-monitoring
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
