apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-k8s-openshift-customer-monitoring
  namespace: openshift-customer-monitoring
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-customer-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s-openshift-customer-monitoring
