apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backplane-cee-pcap-collector
  namespace: openshift-backplane-managed-scripts
rules:
# can create cred secret for mustgathers
# Enables https://github.com/openshift/managed-scripts/blob/main/scripts/CEE/pcap-collector/metadata.yaml, which requires users to be able to create/get/delete the pcap-collector-creds secret in the managed scripts ns
- verbs:
    - "create"
    - "delete"
  apiGroups:
    - ""
  resources:
    - "secrets"
  resourceNames:
    - "pcap-collector-creds"
### END
