apiVersion: v1
kind: ServiceAccount
metadata:
  name: osd-backplane
  namespace: openshift-backplane-managed-scripts
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: osd-delete-backplane-script-resources
  namespace: openshift-backplane-managed-scripts
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - serviceaccounts
    verbs:
      - get
      - list
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: osd-delete-backplane-script-resources
  namespace: openshift-backplane-managed-scripts
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: osd-delete-backplane-script-resources
subjects:
- kind: ServiceAccount
  name: osd-backplane
  namespace: openshift-backplane-managed-scripts
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: osd-delete-backplane-script-resources
rules:
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs:
      - get
      - list
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: osd-delete-backplane-script-resources
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: osd-delete-backplane-script-resources
subjects:
- kind: ServiceAccount
  name: osd-backplane
  namespace: openshift-backplane-managed-scripts
