deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
  # Enable in-cluster logging alerts for those clusters that already have logging installed
  # https://issues.redhat.com/browse/OSD-7564
  - key: ext-managed.openshift.io/extended-logging-support
    operator: In
    values: ["true"]
