apiVersion: managed.openshift.io/v1alpha1
kind: SubjectPermission
metadata:
  name: backplane-mtsre-openshift-connectors-admins
  namespace: openshift-rbac-permissions
spec:
  permissions:
  - clusterRoleName: admin
    namespacesAllowedRegex: (^redhat-openshift-connectors$)
  - clusterRoleName: backplane-openshift-connectors-cr-admins
    namespacesAllowedRegex: (^redhat-openshift-connectors$)
  - clusterRoleName: backplane-mtsre-monitoring
    namespacesAllowedRegex: (^redhat-openshift-connectors$)
  subjectKind: Group
  subjectName: system:serviceaccounts:openshift-backplane-mtsre
