apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sre-pruner-buildsdeploys-pruning
roleRef:
  kind: ClusterRole
  name: sre-pruner-buildsdeploys-cr
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: sre-pruner-sa
  namespace: openshift-sre-pruning
