apiVersion: managed.openshift.io/v1alpha1
kind: SubjectPermission
metadata:
  name: backplane-lpsre-cert-manager-project
  namespace: openshift-rbac-permissions
spec:
  permissions:
  - clusterRoleName: view
    namespacesAllowedRegex: (^redhat-cert-manager-operator$)
  subjectKind: Group
  subjectName: system:serviceaccounts:openshift-backplane-lpsre
