apiVersion: managed.openshift.io/v1alpha1
kind: SubjectPermission
metadata:
  name: backplane-rhoam-cssre-admins
  namespace: openshift-rbac-permissions
spec:
  permissions:
  - clusterRoleName: backplane-rhoam-cssre-admins-project
    namespacesAllowedRegex: (^redhat-rhoami?$|^redhat-rhoami?-.*)
  - clusterRoleName: view
    namespacesAllowedRegex: (^redhat-rhoami?$|^redhat-rhoami?-.*)
  subjectKind: Group
  subjectName: system:serviceaccounts:openshift-backplane-cssre
