apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-upgrade-managed-notification-alerts
    role: alert-rules 
  name: sre-upgrade-send-managed-notification-alerts
  namespace: openshift-monitoring
spec:
  groups:
  - name: sre-upgrade-managed-notification-alerts
    rules:
    - alert: UpgradeControlPlaneUpgradeTimeoutNotificationSRE
      expr: count(ALERTS{alertname="UpgradeControlPlaneUpgradeTimeoutSRE", alertstate="firing"}) >= 1
      for: 30m
      labels:
        severity: info
        namespace: openshift-monitoring
        managed_notification_template: "UpgradeControlPlaneUpgradeTimeout"
        send_managed_notification: "true"
      annotations:
        summary: "Controlplane upgrade timeout for {{ $labels.version }}"
        description: "controlplane upgrade for {{ $labels.version }} cannot be finished in the given time period"