apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-proxy-managed-notification-alerts
    role: alert-rules 
  name: sre-proxy-managed-notification-alerts
  namespace: openshift-monitoring
spec:
  groups:
  - name: sre-proxy-managed-notification-alerts
    rules:
    - alert: AdditionalTrustBundleCAExpiringNotificationSRE
      expr: cluster_proxy_ca_expiry_timestamp{name="osd_exporter"} - time() < 86400 * 30 > 0
      for: 10m
      labels:
        severity: Info
        namespace: openshift-monitoring
        managed_notification_template: "AdditionalTrustBundleCAExpiring"
        send_managed_notification: "true"
      annotations:
        message: "Additional Trust Bundle CA certificate will expire in {{ $value | humanizeDuration }}. Ensure new certificate is provided prior to expiration to avoid cluster degradation and/or unavailability"
    - alert: AdditionalTrustBundleCAExpiredNotificationSRE
      expr: cluster_proxy_ca_expiry_timestamp{name="osd_exporter"} - time() <= 0
      for: 10m
      labels:
        severity: Info
        namespace: openshift-monitoring
        managed_notification_template: "AdditionalTrustBundleCAExpired"
        send_managed_notification: "true"        
      annotations:
        message: "Additional Trust Bundle CA certificate will expire in {{ $value | humanizeDuration }}. Ensure new certificate is provided prior to expiration to avoid cluster degradation and/or unavailability"
    - alert: AdditionalTrustBundleCAInvalidNotificationSRE
      expr: cluster_operator_conditions{job="cluster-version-operator", name="network", condition="Degraded",reason="TrustBundleValidationFailure"} == 1
      for: 5m
      labels:
        severity: Info
        namespace: openshift-monitoring
        managed_notification_template: "AdditionalTrustBundleCAInvalid"
        send_managed_notification: "true"
      annotations:
        message: "Cluster proxy CA has failed validation. Ensure the CA is PEM-encoded X.509."
    - alert: ClusterProxyNetworkDegradedNotificationSRE
      expr: cluster_operator_conditions{job="cluster-version-operator", name="network", condition="Degraded",reason="InvalidProxyConfig"} == 1
      for: 10m
      labels:
        severity: Info
        namespace: openshift-monitoring
        managed_notification_template: "ClusterProxyNetworkDegraded"
        send_managed_notification: "true"
      annotations:
        message: "Cluster proxy is failing network readiness endpoint checks and may be misconfigured or not running."