apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backplane-tam-mustgather
  namespace: openshift-must-gather-operator
rules:
# can create cred secret for mustgathers
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create 
# can create mustgathers CR
- apiGroups:
  - managed.openshift.io
  resources:
  - mustgathers
  verbs:
  - create
  - delete
### END