---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ocpbugs-773
  namespace: openshift-sre-pruning
  annotations:
    kubernetes.io/description: Mitigate https://issues.redhat.com/browse/OCPBUGS-773 by checking podman version
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
